# Generated by Django 4.2.3 on 2023-09-16 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0051_remove_professionalsalarycalculation_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalsalarycalculation',
            name='grossDed',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='professionalsalarycalculation',
            name='grossEarn',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='professionalsalarycalculation',
            name='incomeT',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='professionalsalarycalculation',
            name='netSal',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='professionalsalarycalculation',
            name='other_deduction',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='professionalsalarycalculation',
            name='other_earning',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='professionalsalarycalculation',
            name='profIncentive',
            field=models.FloatField(default=0.0),
        ),
    ]
