# Generated by Django 4.2.3 on 2023-09-16 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0053_alter_professionalsalarycalculation_empcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionalSalaryCal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empName', models.TextField(default='None')),
                ('payDays', models.PositiveIntegerField(default=0)),
                ('appSalary', models.FloatField(default=0.0)),
                ('professionalFees', models.FloatField(default=0.0)),
                ('other_earning', models.FloatField(default=0.0)),
                ('other_deduction', models.FloatField(default=0.0)),
                ('profIncentive', models.FloatField(default=0.0)),
                ('grossEarn', models.FloatField(default=0.0)),
                ('incomeT', models.FloatField(default=0.0)),
                ('grossDed', models.FloatField(default=0.0)),
                ('netSal', models.FloatField(default=0.0)),
                ('month', models.CharField(default='None', max_length=15)),
                ('year', models.PositiveIntegerField(default=0)),
                ('empcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employeedetail')),
            ],
            options={
                'db_table': 'ProfessionalSalaryCal',
            },
        ),
    ]
