# Generated by Django 4.2.3 on 2023-09-16 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0054_professionalsalarycal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salarycalculation',
            name='id',
        ),
        migrations.AlterField(
            model_name='salarycalculation',
            name='staff_salary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='employee.staffsalary'),
        ),
        migrations.CreateModel(
            name='StaffSalaryStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic', models.FloatField(default=0.0)),
                ('hra', models.FloatField(default=0.0)),
                ('specialAll', models.FloatField(default=0.0)),
                ('grossS', models.FloatField(default=0.0)),
                ('start_month', models.CharField(default='None', max_length=15)),
                ('start_year', models.PositiveIntegerField(default=0)),
                ('end_month', models.CharField(default='None', max_length=15)),
                ('end_year', models.PositiveIntegerField(default=0)),
                ('empcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employeedetail')),
            ],
            options={
                'db_table': 'StaffSalaryStructure',
            },
        ),
    ]
