# Generated by Django 4.2.3 on 2023-09-16 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0055_remove_salarycalculation_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffsalarystructure',
            name='empName',
            field=models.CharField(default='None', max_length=200),
        ),
    ]
