# Generated by Django 4.2.3 on 2023-09-16 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0057_staffsalarycalculation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffsalarycalculation',
            name='month',
            field=models.CharField(default='None', max_length=15),
        ),
    ]
