# Generated by Django 4.2.3 on 2023-09-16 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0059_staffsalarycalculation_professional_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalsalarycal',
            name='lop',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
