# Generated by Django 4.2.3 on 2023-09-17 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0060_professionalsalarycal_lop'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffsalarycalculation',
            name='lop',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
