# Generated by Django 4.2.3 on 2023-09-17 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0061_staffsalarycalculation_lop'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffsalarycalculation',
            name='empName',
            field=models.TextField(default='None'),
        ),
        migrations.AlterModelTable(
            name='staffsalarycalculation',
            table='StaffSalaryCalculation',
        ),
    ]
